export const ISABELLA_LEARNING_API = [
  {
    id: "learning.ingest",
    domain: "heads",
    method: "POST",
    path: "/v1/isabella/learning/ingest",
    auth: "OIDC+tenant+scope+consent",
    idempotency: true,
    audit: true,
    status: "implemented" as const,
    description: "Ingesta auditable de ejemplos supervisados, episodios, preferencias y procedimientos.",
    requestSchema: "LearningIngestApiSchema",
    responseSchema: "LearningResult",
  },
  {
    id: "learning.retrieve",
    domain: "memory",
    method: "POST",
    path: "/v1/isabella/learning/retrieve",
    auth: "OIDC+tenant+scope",
    idempotency: false,
    audit: true,
    status: "implemented" as const,
    description: "Recuperación de conocimiento aprendido por conceptos y relevancia.",
    requestSchema: "LearningQueryApiSchema",
    responseSchema: "LearningMemory[]",
  },
  {
    id: "learning.evaluate",
    domain: "heads",
    method: "POST",
    path: "/v1/isabella/learning/evaluate",
    auth: "OIDC+tenant+scope",
    idempotency: false,
    audit: true,
    status: "implemented" as const,
    description: "Evalúa cobertura y calidad de conocimiento aprendido para una consulta.",
    requestSchema: "LearningEvaluateApiSchema",
    responseSchema: "LearningEvaluation",
  },
  {
    id: "learning.snapshot",
    domain: "memory",
    method: "GET",
    path: "/v1/isabella/learning/snapshot",
    auth: "OIDC+tenant+scope+admin",
    idempotency: false,
    audit: true,
    status: "implemented" as const,
    description: "Obtiene snapshot versionado del estado de aprendizaje para respaldo y auditoría.",
    responseSchema: "LearningSnapshot",
  },
] as const;
