/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PakeRouteImport } from './routes/pake'
import { Route as ApiBillingRouteImport } from './routes/api/billing'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiDbRouteImport } from './routes/api/db'
import { Route as ApiEconomicIntegrityRouteImport } from './routes/api/economic-integrity'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiIntelligenceRouteImport } from './routes/api/intelligence'
import { Route as ApiIsabellaRouteImport } from './routes/api/isabella'
import { Route as ApiIsabellaCognitiveTrainingRouteImport } from './routes/api/isabella-cognitive-training'
import { Route as ApiIsabellaLearningRouteImport } from './routes/api/isabella-learning'
import { Route as ApiIsabellaSkillsRouteImport } from './routes/api/isabella-skills'
import { Route as ApiIsabellaVoiceRouteImport } from './routes/api/isabella-voice'
import { Route as ApiMuxIntroRouteImport } from './routes/api/mux-intro'
import { Route as ApiSecurityRouteImport } from './routes/api/security'
import { Route as ApiHealthDeepRouteImport } from './routes/api/health/deep'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiIsabellaNativeRouteImport } from './routes/api/isabella.native'
import { Route as ApiV1IsabellaRouteImport } from './routes/api/v1/isabella'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PakeRoute = PakeRouteImport.update({
  id: '/pake',
  path: '/pake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingRoute = ApiBillingRouteImport.update({
  id: '/api/billing',
  path: '/api/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbRoute = ApiDbRouteImport.update({
  id: '/api/db',
  path: '/api/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEconomicIntegrityRoute = ApiEconomicIntegrityRouteImport.update({
  id: '/api/economic-integrity',
  path: '/api/economic-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntelligenceRoute = ApiIntelligenceRouteImport.update({
  id: '/api/intelligence',
  path: '/api/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIsabellaRoute = ApiIsabellaRouteImport.update({
  id: '/api/isabella',
  path: '/api/isabella',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIsabellaCognitiveTrainingRoute =
  ApiIsabellaCognitiveTrainingRouteImport.update({
    id: '/api/isabella-cognitive-training',
    path: '/api/isabella-cognitive-training',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIsabellaLearningRoute = ApiIsabellaLearningRouteImport.update({
  id: '/api/isabella-learning',
  path: '/api/isabella-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIsabellaSkillsRoute = ApiIsabellaSkillsRouteImport.update({
  id: '/api/isabella-skills',
  path: '/api/isabella-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIsabellaVoiceRoute = ApiIsabellaVoiceRouteImport.update({
  id: '/api/isabella-voice',
  path: '/api/isabella-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMuxIntroRoute = ApiMuxIntroRouteImport.update({
  id: '/api/mux-intro',
  path: '/api/mux-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityRoute = ApiSecurityRouteImport.update({
  id: '/api/security',
  path: '/api/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthDeepRoute = ApiHealthDeepRouteImport.update({
  id: '/deep',
  path: '/deep',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiIsabellaNativeRoute = ApiIsabellaNativeRouteImport.update({
  id: '/native',
  path: '/native',
  getParentRoute: () => ApiIsabellaRoute,
} as any)
const ApiV1IsabellaRoute = ApiV1IsabellaRouteImport.update({
  id: '/api/v1/isabella',
  path: '/api/v1/isabella',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pake': typeof PakeRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/db': typeof ApiDbRoute
  '/api/economic-integrity': typeof ApiEconomicIntegrityRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/intelligence': typeof ApiIntelligenceRoute
  '/api/isabella': typeof ApiIsabellaRouteWithChildren
  '/api/isabella-cognitive-training': typeof ApiIsabellaCognitiveTrainingRoute
  '/api/isabella-learning': typeof ApiIsabellaLearningRoute
  '/api/isabella-skills': typeof ApiIsabellaSkillsRoute
  '/api/isabella-voice': typeof ApiIsabellaVoiceRoute
  '/api/mux-intro': typeof ApiMuxIntroRoute
  '/api/security': typeof ApiSecurityRoute
  '/api/health/deep': typeof ApiHealthDeepRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/isabella/native': typeof ApiIsabellaNativeRoute
  '/api/v1/isabella': typeof ApiV1IsabellaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pake': typeof PakeRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/db': typeof ApiDbRoute
  '/api/economic-integrity': typeof ApiEconomicIntegrityRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/intelligence': typeof ApiIntelligenceRoute
  '/api/isabella': typeof ApiIsabellaRouteWithChildren
  '/api/isabella-cognitive-training': typeof ApiIsabellaCognitiveTrainingRoute
  '/api/isabella-learning': typeof ApiIsabellaLearningRoute
  '/api/isabella-skills': typeof ApiIsabellaSkillsRoute
  '/api/isabella-voice': typeof ApiIsabellaVoiceRoute
  '/api/mux-intro': typeof ApiMuxIntroRoute
  '/api/security': typeof ApiSecurityRoute
  '/api/health/deep': typeof ApiHealthDeepRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/isabella/native': typeof ApiIsabellaNativeRoute
  '/api/v1/isabella': typeof ApiV1IsabellaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pake': typeof PakeRoute
  '/api/billing': typeof ApiBillingRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/db': typeof ApiDbRoute
  '/api/economic-integrity': typeof ApiEconomicIntegrityRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/intelligence': typeof ApiIntelligenceRoute
  '/api/isabella': typeof ApiIsabellaRouteWithChildren
  '/api/isabella-cognitive-training': typeof ApiIsabellaCognitiveTrainingRoute
  '/api/isabella-learning': typeof ApiIsabellaLearningRoute
  '/api/isabella-skills': typeof ApiIsabellaSkillsRoute
  '/api/isabella-voice': typeof ApiIsabellaVoiceRoute
  '/api/mux-intro': typeof ApiMuxIntroRoute
  '/api/security': typeof ApiSecurityRoute
  '/api/health/deep': typeof ApiHealthDeepRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/isabella/native': typeof ApiIsabellaNativeRoute
  '/api/v1/isabella': typeof ApiV1IsabellaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pake'
    | '/api/billing'
    | '/api/catalog'
    | '/api/db'
    | '/api/economic-integrity'
    | '/api/health'
    | '/api/intelligence'
    | '/api/isabella'
    | '/api/isabella-cognitive-training'
    | '/api/isabella-learning'
    | '/api/isabella-skills'
    | '/api/isabella-voice'
    | '/api/mux-intro'
    | '/api/security'
    | '/api/health/deep'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/isabella/native'
    | '/api/v1/isabella'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pake'
    | '/api/billing'
    | '/api/catalog'
    | '/api/db'
    | '/api/economic-integrity'
    | '/api/health'
    | '/api/intelligence'
    | '/api/isabella'
    | '/api/isabella-cognitive-training'
    | '/api/isabella-learning'
    | '/api/isabella-skills'
    | '/api/isabella-voice'
    | '/api/mux-intro'
    | '/api/security'
    | '/api/health/deep'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/isabella/native'
    | '/api/v1/isabella'
  id:
    | '__root__'
    | '/'
    | '/pake'
    | '/api/billing'
    | '/api/catalog'
    | '/api/db'
    | '/api/economic-integrity'
    | '/api/health'
    | '/api/intelligence'
    | '/api/isabella'
    | '/api/isabella-cognitive-training'
    | '/api/isabella-learning'
    | '/api/isabella-skills'
    | '/api/isabella-voice'
    | '/api/mux-intro'
    | '/api/security'
    | '/api/health/deep'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/isabella/native'
    | '/api/v1/isabella'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PakeRoute: typeof PakeRoute
  ApiBillingRoute: typeof ApiBillingRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiDbRoute: typeof ApiDbRoute
  ApiEconomicIntegrityRoute: typeof ApiEconomicIntegrityRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiIntelligenceRoute: typeof ApiIntelligenceRoute
  ApiIsabellaRoute: typeof ApiIsabellaRouteWithChildren
  ApiIsabellaCognitiveTrainingRoute: typeof ApiIsabellaCognitiveTrainingRoute
  ApiIsabellaLearningRoute: typeof ApiIsabellaLearningRoute
  ApiIsabellaSkillsRoute: typeof ApiIsabellaSkillsRoute
  ApiIsabellaVoiceRoute: typeof ApiIsabellaVoiceRoute
  ApiMuxIntroRoute: typeof ApiMuxIntroRoute
  ApiSecurityRoute: typeof ApiSecurityRoute
  ApiV1IsabellaRoute: typeof ApiV1IsabellaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pake': {
      id: '/pake'
      path: '/pake'
      fullPath: '/pake'
      preLoaderRoute: typeof PakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing': {
      id: '/api/billing'
      path: '/api/billing'
      fullPath: '/api/billing'
      preLoaderRoute: typeof ApiBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db': {
      id: '/api/db'
      path: '/api/db'
      fullPath: '/api/db'
      preLoaderRoute: typeof ApiDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/economic-integrity': {
      id: '/api/economic-integrity'
      path: '/api/economic-integrity'
      fullPath: '/api/economic-integrity'
      preLoaderRoute: typeof ApiEconomicIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intelligence': {
      id: '/api/intelligence'
      path: '/api/intelligence'
      fullPath: '/api/intelligence'
      preLoaderRoute: typeof ApiIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella': {
      id: '/api/isabella'
      path: '/api/isabella'
      fullPath: '/api/isabella'
      preLoaderRoute: typeof ApiIsabellaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella-cognitive-training': {
      id: '/api/isabella-cognitive-training'
      path: '/api/isabella-cognitive-training'
      fullPath: '/api/isabella-cognitive-training'
      preLoaderRoute: typeof ApiIsabellaCognitiveTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella-learning': {
      id: '/api/isabella-learning'
      path: '/api/isabella-learning'
      fullPath: '/api/isabella-learning'
      preLoaderRoute: typeof ApiIsabellaLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella-skills': {
      id: '/api/isabella-skills'
      path: '/api/isabella-skills'
      fullPath: '/api/isabella-skills'
      preLoaderRoute: typeof ApiIsabellaSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/isabella-voice': {
      id: '/api/isabella-voice'
      path: '/api/isabella-voice'
      fullPath: '/api/isabella-voice'
      preLoaderRoute: typeof ApiIsabellaVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mux-intro': {
      id: '/api/mux-intro'
      path: '/api/mux-intro'
      fullPath: '/api/mux-intro'
      preLoaderRoute: typeof ApiMuxIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security': {
      id: '/api/security'
      path: '/api/security'
      fullPath: '/api/security'
      preLoaderRoute: typeof ApiSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/deep': {
      id: '/api/health/deep'
      path: '/deep'
      fullPath: '/api/health/deep'
      preLoaderRoute: typeof ApiHealthDeepRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/isabella/native': {
      id: '/api/isabella/native'
      path: '/native'
      fullPath: '/api/isabella/native'
      preLoaderRoute: typeof ApiIsabellaNativeRouteImport
      parentRoute: typeof ApiIsabellaRoute
    }
    '/api/v1/isabella': {
      id: '/api/v1/isabella'
      path: '/api/v1/isabella'
      fullPath: '/api/v1/isabella'
      preLoaderRoute: typeof ApiV1IsabellaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiHealthRouteChildren {
  ApiHealthDeepRoute: typeof ApiHealthDeepRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthDeepRoute: ApiHealthDeepRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

interface ApiIsabellaRouteChildren {
  ApiIsabellaNativeRoute: typeof ApiIsabellaNativeRoute
}

const ApiIsabellaRouteChildren: ApiIsabellaRouteChildren = {
  ApiIsabellaNativeRoute: ApiIsabellaNativeRoute,
}

const ApiIsabellaRouteWithChildren = ApiIsabellaRoute._addFileChildren(
  ApiIsabellaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PakeRoute: PakeRoute,
  ApiBillingRoute: ApiBillingRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiDbRoute: ApiDbRoute,
  ApiEconomicIntegrityRoute: ApiEconomicIntegrityRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiIntelligenceRoute: ApiIntelligenceRoute,
  ApiIsabellaRoute: ApiIsabellaRouteWithChildren,
  ApiIsabellaCognitiveTrainingRoute: ApiIsabellaCognitiveTrainingRoute,
  ApiIsabellaLearningRoute: ApiIsabellaLearningRoute,
  ApiIsabellaSkillsRoute: ApiIsabellaSkillsRoute,
  ApiIsabellaVoiceRoute: ApiIsabellaVoiceRoute,
  ApiMuxIntroRoute: ApiMuxIntroRoute,
  ApiSecurityRoute: ApiSecurityRoute,
  ApiV1IsabellaRoute: ApiV1IsabellaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
