-- Isabella TINA — runtime integrity / durable governance
-- 2026-10-01
-- Idempotent compatibility migration for policy, decision ledger and kill-switch.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.prevent_bookpi_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'append_only_violation: % cannot be mutated', TG_TABLE_NAME;
END;
$$;

CREATE TABLE IF NOT EXISTS public.isabella_policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  policy_key TEXT NOT NULL UNIQUE,
  description TEXT,
  rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  version TEXT NOT NULL DEFAULT '1.0.0',
  priority INTEGER NOT NULL DEFAULT 100,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_isabella_policies_rules_is_array
    CHECK (jsonb_typeof(rules) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_isabella_policies_priority
  ON public.isabella_policies (priority, policy_key)
  WHERE enabled = TRUE;

CREATE TABLE IF NOT EXISTS public.isabella_decisions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id TEXT NOT NULL,
  actor_id TEXT,
  authority TEXT,
  capability TEXT,
  policy TEXT,
  risk TEXT,
  model_id TEXT,
  input_hash TEXT,
  output_hash TEXT,
  result TEXT,
  previous_hash TEXT,
  record_hash TEXT,
  evidence_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  append_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
  CONSTRAINT chk_isabella_decisions_evidence_is_array
    CHECK (jsonb_typeof(evidence_ids) = 'array')
);

ALTER TABLE public.isabella_decisions
  ADD COLUMN IF NOT EXISTS actor_id TEXT,
  ADD COLUMN IF NOT EXISTS authority TEXT,
  ADD COLUMN IF NOT EXISTS capability TEXT,
  ADD COLUMN IF NOT EXISTS policy TEXT,
  ADD COLUMN IF NOT EXISTS risk TEXT,
  ADD COLUMN IF NOT EXISTS model_id TEXT,
  ADD COLUMN IF NOT EXISTS input_hash TEXT,
  ADD COLUMN IF NOT EXISTS output_hash TEXT,
  ADD COLUMN IF NOT EXISTS result TEXT,
  ADD COLUMN IF NOT EXISTS previous_hash TEXT,
  ADD COLUMN IF NOT EXISTS record_hash TEXT,
  ADD COLUMN IF NOT EXISTS evidence_ids JSONB,
  ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS append_seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

UPDATE public.isabella_decisions
SET evidence_ids = COALESCE(evidence_ids, '[]'::jsonb),
    recorded_at = COALESCE(recorded_at, created_at, NOW())
WHERE evidence_ids IS NULL OR recorded_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_isabella_decisions_tenant_chain
  ON public.isabella_decisions (tenant_id, append_seq DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_isabella_decisions_record_hash
  ON public.isabella_decisions (tenant_id, record_hash)
  WHERE record_hash IS NOT NULL;

ALTER TABLE public.isabella_policies ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.isabella_policies FROM anon, authenticated;
ALTER TABLE public.isabella_decisions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.isabella_decisions FROM anon, authenticated;

DROP TRIGGER IF EXISTS trg_prevent_isabella_decisions_update ON public.isabella_decisions;
CREATE TRIGGER trg_prevent_isabella_decisions_update
BEFORE UPDATE ON public.isabella_decisions
FOR EACH ROW
EXECUTE FUNCTION public.prevent_bookpi_mutation();

DROP TRIGGER IF EXISTS trg_prevent_isabella_decisions_delete ON public.isabella_decisions;
CREATE TRIGGER trg_prevent_isabella_decisions_delete
BEFORE DELETE ON public.isabella_decisions
FOR EACH ROW
EXECUTE FUNCTION public.prevent_bookpi_mutation();

CREATE TABLE IF NOT EXISTS public.kill_switch_state (
  capability TEXT PRIMARY KEY,
  engaged BOOLEAN NOT NULL DEFAULT FALSE,
  reason TEXT,
  actor_id TEXT,
  engaged_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.kill_switch_state ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.kill_switch_state FROM anon, authenticated;

INSERT INTO public.isabella_policies (policy_key, description, rules, version, priority)
VALUES
  ('p-critical-risk-blocked',
   'Riesgo critical: la ejecución queda denegada por política DB.',
   '[{"when":{"risk":"critical"},"then":{"status":"denied","reason":"riesgo_critico_bloqueado"}}]'::jsonb,
   '1.0.0', 10),
  ('p-territorial-boundary-blocked',
   'Herramientas con territorialBoundary=true quedan bloqueadas.',
   '[{"when":{"territorialBoundary":true},"then":{"status":"denied","reason":"frontera_territorial_bloqueada"}}]'::jsonb,
   '1.0.0', 20),
  ('p-high-risk-approval',
   'Riesgo high requiere aprobación humana previa.',
   '[{"when":{"risk":"high"},"then":{"status":"requires_approval","reason":"riesgo_alto_requiere_aprobacion"}}]'::jsonb,
   '1.0.0', 30),
  ('p-unauthenticated-review',
   'Actores no autenticados requieren revisión antes de ejecutar.',
   '[{"when":{"authenticated":false},"then":{"status":"requires_approval","reason":"actor_no_autenticado_requiere_revision"}}]'::jsonb,
   '1.0.0', 40),
  ('p-identity-tools-approval',
   'Herramientas de identidad pasan por aprobación humana.',
   '[{"when":{"category":"identity"},"then":{"status":"requires_approval","reason":"herramienta_identidad_requiere_aprobacion"}}]'::jsonb,
   '1.0.0', 50)
ON CONFLICT (policy_key) DO UPDATE SET
  description = EXCLUDED.description,
  rules = EXCLUDED.rules,
  version = EXCLUDED.version,
  priority = EXCLUDED.priority,
  enabled = TRUE,
  updated_at = NOW();
