export const SCHEMA_TABLES = [
  {
    name: "isabella_memories",
    scope: "tenant/session",
    purpose: "Tenant-scoped hierarchical memory.",
  },
  {
    name: "isabella_audit_logs",
    scope: "tenant",
    purpose: "Append-only governance and audit events.",
  },
  { name: "isabella_decisions", scope: "tenant", purpose: "Policy and decision records." },
  { name: "isabella_tool_runs", scope: "tenant", purpose: "Authorized tool execution outcomes." },
  { name: "isabella_policies", scope: "global/server-only", purpose: "Versioned policy-as-code." },
  {
    name: "kill_switch_state",
    scope: "global/server-only",
    purpose: "Durable emergency capability state.",
  },
] as const;

export const ISABELLA_SQL_MIGRATION = `
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.prevent_bookpi_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'append_only_violation: % cannot be mutated', TG_TABLE_NAME;
END;
$$;

CREATE TABLE IF NOT EXISTS isabella_memories (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  scope text not null default 'session',
  content jsonb not null,
  created_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS isabella_memories_tenant_scope_idx
  ON isabella_memories (tenant_id, scope, created_at desc);

CREATE TABLE IF NOT EXISTS isabella_audit_logs (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS isabella_audit_logs_tenant_created_idx
  ON isabella_audit_logs (tenant_id, created_at desc);

CREATE TABLE IF NOT EXISTS isabella_policies (
  id uuid primary key default gen_random_uuid(),
  policy_key text not null unique,
  description text,
  rules jsonb not null default '[]'::jsonb,
  version text not null default '1.0.0',
  priority integer not null default 100,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint isabella_policies_rules_array check (jsonb_typeof(rules) = 'array')
);

CREATE TABLE IF NOT EXISTS isabella_decisions (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  actor_id text,
  authority text,
  capability text,
  policy text,
  risk text,
  model_id text,
  input_hash text,
  output_hash text,
  result text,
  previous_hash text,
  record_hash text,
  evidence_ids jsonb not null default '[]'::jsonb,
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  append_seq bigint generated by default as identity,
  constraint isabella_decisions_evidence_array check (jsonb_typeof(evidence_ids) = 'array')
);

ALTER TABLE isabella_decisions
  ADD COLUMN IF NOT EXISTS actor_id text,
  ADD COLUMN IF NOT EXISTS authority text,
  ADD COLUMN IF NOT EXISTS capability text,
  ADD COLUMN IF NOT EXISTS policy text,
  ADD COLUMN IF NOT EXISTS risk text,
  ADD COLUMN IF NOT EXISTS model_id text,
  ADD COLUMN IF NOT EXISTS input_hash text,
  ADD COLUMN IF NOT EXISTS output_hash text,
  ADD COLUMN IF NOT EXISTS result text,
  ADD COLUMN IF NOT EXISTS previous_hash text,
  ADD COLUMN IF NOT EXISTS record_hash text,
  ADD COLUMN IF NOT EXISTS evidence_ids jsonb,
  ADD COLUMN IF NOT EXISTS recorded_at timestamptz,
  ADD COLUMN IF NOT EXISTS append_seq bigint generated by default as identity;

UPDATE isabella_decisions
   SET evidence_ids = coalesce(evidence_ids, '[]'::jsonb),
       recorded_at = coalesce(recorded_at, created_at, now())
 WHERE evidence_ids is null OR recorded_at is null;

CREATE INDEX IF NOT EXISTS isabella_decisions_chain_idx
  ON isabella_decisions (tenant_id, append_seq desc);

CREATE UNIQUE INDEX IF NOT EXISTS isabella_decisions_record_hash_uq
  ON isabella_decisions (tenant_id, record_hash)
  WHERE record_hash is not null;

ALTER TABLE isabella_policies ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON isabella_policies FROM anon, authenticated;
ALTER TABLE isabella_decisions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON isabella_decisions FROM anon, authenticated;

DROP TRIGGER IF EXISTS trg_prevent_isabella_decisions_update ON isabella_decisions;
CREATE TRIGGER trg_prevent_isabella_decisions_update
BEFORE UPDATE ON isabella_decisions
FOR EACH ROW EXECUTE FUNCTION public.prevent_bookpi_mutation();

DROP TRIGGER IF EXISTS trg_prevent_isabella_decisions_delete ON isabella_decisions;
CREATE TRIGGER trg_prevent_isabella_decisions_delete
BEFORE DELETE ON isabella_decisions
FOR EACH ROW EXECUTE FUNCTION public.prevent_bookpi_mutation();

CREATE TABLE IF NOT EXISTS kill_switch_state (
  capability text primary key,
  engaged boolean not null default false,
  reason text,
  actor_id text,
  engaged_at timestamptz,
  released_at timestamptz,
  updated_at timestamptz not null default now()
);
ALTER TABLE kill_switch_state ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON kill_switch_state FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS isabella_tool_runs (
  id uuid primary key default gen_random_uuid(),
  tenant_id text not null,
  tool_name text not null,
  status text not null,
  result jsonb,
  created_at timestamptz not null default now()
);
`;
